add types to packages
Klarr-Agency/Circum-Icons pull request #24
Opened 2024-04-12 06:42 UTC by melosh101

added types to the following packages:
circum-icons-react
circum-icons-svelte
circum-icons-vue

big changes:
svelte has been ported to use ts and sveltekit instead of rollup for simplicity, but it also changes the export from a default to a "normal export"

2024-04-12 06:57 UTC, melosh101 commented
forgot to add that i havent bumped any package versions since i thought you'd might want to do that

2024-04-13 13:32 UTC, Klarr-Agency commented
Thanks @melosh101 I will review your code today.

2024-04-13 14:06 UTC, Klarr-Agency requested changes
Great work overall! There are a few minor adjustments that could be made, but they are more personal preferences than actual issues. Thank you for your time and contribution to this open-source project. It's not often that people are willing to give back, and I appreciate it greatly.

Guillaume

2024-04-20 14:39 UTC, Klarr-Agency approved these changes

2024-04-20 14:42 UTC, Klarr-Agency approved these changes

2024-04-20 14:42 UTC, merged